services:
  api:
    container_name: api
    build:
        context: .
        dockerfile: Api/Dockerfile
    ports:
      - "43695:8080"

  web-app:
    container_name: web-app
    build:
        context: .
        dockerfile: WebApp/Dockerfile
    ports:
      - "56088:8080"
    environment:
      - ApiSettings__Url=http://api:8080